### PR TITLE
Power8/LE SIMD Support

### LINKED ISSUE #9: IBM-HPC: does not build on Power8 with GCC due to vector unit checking and instrinsics
We are trying to build hh-suite on Power8.  Our configuration looks like:

```
git clone https://github.com/soedinglab/hh-suite.git
cd hh-suite
git submodule init
git submodule update
mkdir build && cd build

#requires recent cmake 3.5.1 was used
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/um-ppc64le/hh-suite ..
```

Appears from the error message that cmake checks for SSSE3 and then the code uses abstracted versions of different vector calls in `src/simd.h`.

We would like to add support for Power 8  VSX when compiling on `ppc64le`.  To do this we are assuming

`cmake/CheckSSEFeatures.cmake`
`src/simd.h`

Both need logic added for the VSX intrinsics.  In the end we want a cmake and build that works on Power8.

```
$ cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/um-ppc64le/hh-suite ..
-- The CXX compiler identification is GNU 4.8.3
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler is GNU 
-- Using CPU native flags for SSE optimization:  -march=native
-- Performing Test HAVE_MM_MALLOC
-- Performing Test HAVE_MM_MALLOC - Failed
-- Performing Test HAVE_POSIX_MEMALIGN
-- Performing Test HAVE_POSIX_MEMALIGN - Success
-- Performing Test HAVE_AVX2_EXTENSIONS
-- Performing Test HAVE_AVX2_EXTENSIONS - Failed
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Failed
-- Performing Test HAVE_SSE4_2_EXTENSIONS
-- Performing Test HAVE_SSE4_2_EXTENSIONS - Failed
-- Performing Test HAVE_SSE4_1_EXTENSIONS
-- Performing Test HAVE_SSE4_1_EXTENSIONS - Failed
-- Performing Test HAVE_SSSE3_EXTENSIONS
-- Performing Test HAVE_SSSE3_EXTENSIONS - Failed
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Failed
-- Performing Test HAVE_SSE2_EXTENSIONS
-- Performing Test HAVE_SSE2_EXTENSIONS - Failed
-- Performing Test HAVE_SSE_EXTENSIONS
-- Performing Test HAVE_SSE_EXTENSIONS - Failed
-- No SSE extensions found
CMake Error at src/CMakeLists.txt:26 (message):
  SSSE3 is needed to run compile! CMake will exit.
```

### PR DESCRIPTION
**Pull request by dmiller423**
This PR adds Power8 SIMD code,  and fixes build system to check for processor/arch and only run SSE checks on X86.

This should close #9 and #52 .

### CODE REVIEW

**Comment by dmiller423** [comment]
Ok,  it seems the change I made to: src/hhviterbialgorithm.cpp causes a build error.

const __m128i tmp_vec  = _mm_set_epi32(0x40000000,0x00400000,0x00004000,0x00000040);
to
const simd_int tmp_vec = simdi32_set4(0x40000000,0x00400000,0x00004000,0x00000040);

hhviterbialgorithm.cpp:109:97: error: cannot convert ‘const simd_int {aka const __vector(4) long long int}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m256i _mm256_castsi128_si256(__m128i)’

109:  const simd_int co_vec = _mm256_inserti128_si256(_mm256_castsi128_si256(tmp_vec), tmp_vec, 1);

From the error I think it's using AVX2 and simd_int is _m256i.  
I'm 100% on why it was going about it this way,  if it's constant data can't co_vec be set directly with the proper data using a simd_set*() and alleviate the problem?

Sorry for any inconvenience &| thanks for taking the time to check on my PR.

**Comment by meiermark** [comment]
Can you adjust the travis configuration file (.travis.yml) that it can check the power8 part without compromising the default part? This way I can't merge your pull request.

**Comment by edelsohn** [comment]
Travis currently does not support powerpc64-linux.

**Comment by meiermark** [comment]
There seem to be power8 simulators that work on travis:
https://patchwork.ozlabs.org/patch/422685/

But of course, I never used them. 
According to the output of travis I have to assume that the pull request would destroy the compilation for linux/mac systems.

**Comment by dmiller423** [comment]
The goal here is working SIMD implementation for little endian power8 on linux.
From what I see there is no portable C version,  it requires SSE/AVX.
So I don't think it would change the status of powerpc mac's on linux,  if anything they will be much closer to working.  As I believe they support all of the Altivec SIMD code,  just not VSX.

I will take a look the travis configuration patch after I fix the  issue that causes the build error on x86 hardware.  I hope to have it cleared up today.

**Comment by dmiller423** [comment]
Fixed build issue on x86 / AVX.
Double checked on Power8 LE.

I looked at the travis patch,  I see it installs a power8 simulator which would theoretically allow it to run either a full power8 linux or power8 elf binaries in user mode.   I don't know enough about travis to tell how to set up a specific build system test in the emulator.  I've never seen anyone test non-x86/x64 builds.  I can always provide access to a power8 system via SSH if you want to test the build,  or provide a full build log with appropriate system info beforehand.

Please let me know.

**Comment by martin-steinegger** [comment]
Great work! I'm happy to see that HH-suite goes PowerPC. 
The changes are clean and understandable. Lets merge it.

**Comment by dmiller423** [comment]
Happy to contribute,  if anyone has questions or concerns I always support my work in the future.
Feel free to contact me with them anytime.

**Comment by martin-steinegger** [comment]
@dmiller423 we are currently writing a technical paper for HHsuite3.0 and we would like to mention your work in the text. Is it okay if we write "David Miller has graciously provided his {\tt simd.h} code to support to the AltiVec vector extension of IBM PowerPC CPUs. "

**Comment by dmiller423** [comment]
Certainly 👍

**Pull request merged**
