### PR TITLE
Fixing Altivec Splat Bug

### PR DESCRIPTION
**Pull request by jhuber6**
There was a bug in the Altivec macro expansion for creating vector splats. The casting wasn't being properly applied to the expansion of x in `simdi8_set(x)` in some cases causing the function to return a vector of four integers set to x rather than 16 bytes set to x.

### CODE REVIEW

**Comment by milot-mirdita** [comment]
Maybe these `#define simdf32_add(x,y)    (x + y)` should be  `#define simdf32_add(x,y)    ((x) + (y))`.

Maybe we should do that for every single variable.

**Comment by jhuber6** [comment]
That's a possibility, I could update the file to add in parenthesis around any expression that isn't directly passed to a function.

**Comment by jhuber6** [comment]
This version finally gave me the correct answers when compiled and run on a Power9 processor.

**Comment by milot-mirdita** [comment]
Thanks a lot!
Do the other small tests in `data/test.sh` also produce the same result? Could you also try a `hhblits` search with e.g. the example query in `data/query.a3m` against the `Uniclust/UniRef30 and see if it produces the same results?

**Comment by jhuber6** [comment]
I tested hhalign and hhblits using the single_db data set and they were equivalent. The tests I ran were equivalent as far as I could tell but I couldn't run them all because I didn't have MPI set up. I haven't run it on the Uniclust data set yet because the file is frankly huge. The others at the lab said they would run more tests once the PR was merged.

**Comment by milot-mirdita** [comment]
You could use the Pfam instead for a more reasonable sized database:
http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pfamA_32.0.tar.gz

But fair enough, I'll merge it, thanks again.

**Pull request merged**
