### PR TITLE
Memory sanitizer issues

### PR DESCRIPTION
**Pull request by dvs**
This patch fixes the issues in HHblits tool that have been detected with Clang memory sanitizer (MSAN) which detects the use of uninitialized values and similar misuses of memory access.

Firstly it has confirmed that the latest error in hhviterbialgorithm.cpp (#193) is indeed reported by MSAN. However it also showed that the fix was incomplete &ndash; upper limit of for() loop was wrong.

Secondly it revealed that pred_index and dssp_index arrays are indexed from 0 in hhviterbialgorithm.cpp but filled from 1 in HMMSimd::MapHMMVector.
Also these arrays were not properly filled when HMM in incomplete (i.e. hmms.size < VECSIZE_FLOAT).

After these fixes MSAN doesn't report any warnings during my tests (1 and 2 iterations of HHblits search in PfamA with a large HMM, the test that triggered SEGFAULTs in #193 issue).
Nevertheless please check the changes while considering merge of this pull request, I did my best in verifying this code but it's still highly non-trivial.

This pull request also has two changes for suppressing false warnings from MSAN: zeroing new index structure in ffindex.c and string initialization of character arrays in HMM::HMM() constructor.

### CODE REVIEW

**Comment by dvs** [comment]
P.S. After these changes were applied, Clang Address sanitizer (ASAN) didn't find any issue during the tests. Undefined behaviour sanitizer (UBSAN) detected only one issue (#196).
Tests with thread sanitizer were not performed due to its very low running speed.

**Comment by milot-mirdita** [comment]
Thanks a lot! Martin will review at the indexing issues. 

I am not very happy about the memset though.
If the function is called with `num_max_entries == 0` it will try to actually use tons of real memory instead of tons of virtual memory. You could replace the `malloc` with a `calloc` instead.

**Comment by dvs** [comment]
> I am not very happy about the memset though.
> If the function is called with `num_max_entries == 0` it will try to actually use tons of real memory instead of tons of virtual memory. You could replace the `malloc` with a `calloc` instead.

Sorry, I don't get it.
If `num_max_entries == 0` then `nbytes = sizeof(ffindex_index_t) + 0` and `memset(index, 0, nbytes)` is safe, isn't it?

**Comment by milot-mirdita** [comment]
This part:
```
ffindex_index_t* ffindex_index_parse(FILE *index_file, size_t num_max_entries) {
  if(num_max_entries == 0)
    num_max_entries = FFINDEX_MAX_INDEX_ENTRIES_DEFAULT;
```

This was initially a poor design decision, I think I have removed all ffindex_index_parse calls that take `0` as a size, but I am not 100% sure.

**Comment by dvs** [comment]
OK, I overlooked it.
Then we can make `memset()` conditional:

    if(num_max_entries < FFINDEX_MAX_INDEX_ENTRIES_DEFAULT) {
        memset(index, 0, nbytes); // make clang memory sanitizer happy
    }

Then the cases when `ffindex_index_parse()` is called with `num_max_entries == 0` will cause memory sanitizer warnings, this would even be helpful.

**Comment by milot-mirdita** [comment]
I think a `calloc` instead of `malloc` would also work just fine. It should allocate a single null page and assign it to all the virtual pages, so it should also not run out of real memory.

**Comment by dvs** [comment]
> I think a `calloc` instead of `malloc` would also work just fine. It should allocate a single null page and assign it to all the virtual pages, so it should also not run out of real memory.

I agree.

**Pull request merged**
