### PR TITLE
Changed hhprefiler to use different SSW implementation

### PR DESCRIPTION
**Pull request by stigvp**
* Use mengyao/Complete-Striped-Smith-Waterman-Library implementation instead.
* Add this as a git sub module.

Mengyao's SSW implementation required some changes to make it compatible with HHBlits. I have made these in a fork. So hh-suite will depend on this until that gets integrated into the main one (I have a pending pull request).

Tested with a few different runs of HHBlits. Note that ordering of results is different from previous implementation (but looks correct to me).

Could do with testing across different platforms and further verification of the output.

### CODE REVIEW

**Comment by stigvp** [comment]
Looks like the CI suite can't find the new ssw sub module. Perhaps this needs to be added to a config somewhere?

**Comment by milot-mirdita** [comment]
Thanks a lot! 

It seems like the `lib/ssw` path is missing in the commit. `git add lib/ssw` should fix the problem.
Could you also please replace the C++11 auto and for-range loops with their older C++98 counterparts?

**Comment by stigvp** [comment]
> It seems like the `lib/ssw` path is missing in the commit. `git add lib/ssw` should fix the problem.

It should come in a sub module - the same way lib/ffindex is added. Seems to work fine on a clean install when following instructions here: https://github.com/soedinglab/hh-suite#cloning-from-git - perhaps something needs be configured in Travis somewhere?

> Could you also please replace the C++11 auto and for-range loops with their older C++98 counterparts?

Eek, I didn't realise you require the source to be C++98 compatible. The code I wrote depends on heavily on more recent features, so that would be quite a large change. Feel free to adapt my proposed changes if that helps.

**Comment by ahcm** [comment]
The mengyao ssw lib has a length limitation, right?

**Comment by milot-mirdita** [comment]
> Eek, I didn't realise you require the source to be C++98 compatible. The code I wrote depends on heavily on more recent features, so that would be quite a large change. Feel free to adapt my proposed changes if that helps.

We don't quite require it to be compatible to C++98. We just avoid these two features and prefer to explicitly type out all type information. Just coding style. Stuff like emplace_back is very welcome since we can avoid allocations with it.

**Comment by stigvp** [comment]
> We don't quite require it to be compatible to C++98. We just avoid these two features and prefer to explicitly type out all type information. Just coding style. Stuff like emplace_back is very welcome since we can avoid allocations with it.

Ah, I see. That can certainly be done :)

**Comment by stigvp** [comment]
> The mengyao ssw lib has a length limitation, right?

If I recall correctly, it has a weight size limitation, which was removed by changing some of the types to unsigned ints in my fork of it. Is there another limitation?

**Comment by martin-steinegger** [comment]
@stigvp Thank you for your pull request. I checked your implementation. It seems that you call the SSW library directly without using the simd.h header. This will slow down hhblits if AVX2 is available by 2x. We implemented the SSW library against our simd.h header within MMseqs2 which can be compiled to use either AVX2 or SSE4.1. See:
https://github.com/soedinglab/MMseqs2/blob/master/src/alignment/StripedSmithWaterman.h

@soeding do you know if the ungapped_sse_score code in MMseqs2 was from the original Farrar code or was it developed from Michael Remmert from scratch?

**Comment by stigvp** [comment]
> @stigvp Thank you for your pull request. I checked your implementation. It seems that you call the SSW library directly without using the simd.h header. This will slow down hhblits if AVX2 is available by 2x. We implemented the SSW library against our simd.h header within MMseqs2 which can be compiled to use either AVX2 or SSE4.1. See:
> https://github.com/soedinglab/MMseqs2/blob/master/src/alignment/StripedSmithWaterman.h

Ah, that could well be the case. We haven't explored AVX2 performance much. Let me know if this pull request is still useful to you, or you'd rather do something like what you did for MMseqs2.

**Comment by martin-steinegger** [comment]
I have changed the impl. to the MMseqs2 one, which is based on the     * mengyao/Complete-Striped-Smith-Waterman-Library implementation. See commit 2038c149959e883e840a721f52b03417b898c7b4

**Comment by stigvp** [comment]
> I have changed the impl. to the MMseqs2 one, which is based on the * mengyao/Complete-Striped-Smith-Waterman-Library implementation. See commit [2038c14](https://github.com/soedinglab/hh-suite/commit/2038c149959e883e840a721f52b03417b898c7b4)

Okay, great. I will close this pull request in that case.

**Pull request closed without merging**
